modLoader="javafml"
loaderVersion="[47,)"
license="All Rights Reserved"

[[mods]]
modId="tanshugetrees"
version="6.3.1"
displayName="Tan's Huge Trees"
displayURL="https://legacy.curseforge.com/minecraft/mc-mods/tans-huge-trees"
logoFile="logo.png"
credits="Created with MCreator"
authors="TannyJung"
description="Generate trees and nature stuffs around the world"

# Start of user code block mod configuration
# End of user code block mod configuration

[[dependencies.tanshugetrees]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.20.1]"
    ordering="AFTER"
    side="BOTH"




# Start of user code block dependencies configuration
# End of user code block dependencies configuration