modLoader="javafml"
loaderVersion="[43,)"
license="All Rights Reserved"

[[mods]]
modId="tht"
version="4.4.3"
displayName="Tan's Huge Trees"
displayURL="https://legacy.curseforge.com/members/tannyjung/projects"
logoFile="logo.png"
credits="Created with MCreator"
authors="TannyJung"
description="Generate trees and nature stuffs around the world, improved the look of Minecraft and scale of the world. This mod combined between my command block skills, my small coding skills and MCreator."

# Start of user code block mod configuration
# End of user code block mod configuration

[[dependencies.tht]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.19.2]"
    ordering="AFTER"
    side="BOTH"




# Start of user code block dependencies configuration
# End of user code block dependencies configuration
